name = "BoundaryValueDiffEq"
uuid = "764a87c0-6b3e-53db-9096-fe964310641d"
version = "5.18.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
BoundaryValueDiffEqAscher = "7227322d-7511-4e07-9247-ad6ff830280e"
BoundaryValueDiffEqCore = "56b672f2-a5fe-4263-ab2d-da677488eb3a"
BoundaryValueDiffEqFIRK = "85d9eb09-370e-4000-bb32-543851f73618"
BoundaryValueDiffEqMIRK = "1a22d4ce-7765-49ea-b6f2-13c8438986a6"
BoundaryValueDiffEqMIRKN = "9255f1d6-53bf-473e-b6bd-23f1ff009da4"
BoundaryValueDiffEqShooting = "ed55bfe0-3725-4db6-871e-a1dc9f42a757"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
FastClosures = "9aa1b823-49e4-5ca5-8b0f-3971ec8bab6a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[sources]
BoundaryValueDiffEqAscher = {path = "lib/BoundaryValueDiffEqAscher"}
BoundaryValueDiffEqCore = {path = "lib/BoundaryValueDiffEqCore"}
BoundaryValueDiffEqFIRK = {path = "lib/BoundaryValueDiffEqFIRK"}
BoundaryValueDiffEqMIRK = {path = "lib/BoundaryValueDiffEqMIRK"}
BoundaryValueDiffEqMIRKN = {path = "lib/BoundaryValueDiffEqMIRKN"}
BoundaryValueDiffEqShooting = {path = "lib/BoundaryValueDiffEqShooting"}

[weakdeps]
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"

[extensions]
BoundaryValueDiffEqODEInterfaceExt = "ODEInterface"

[compat]
ADTypes = "1.14"
Aqua = "0.8.11"
BoundaryValueDiffEqAscher = "1"
BoundaryValueDiffEqCore = "1"
BoundaryValueDiffEqFIRK = "1"
BoundaryValueDiffEqMIRK = "1"
BoundaryValueDiffEqMIRKN = "1"
BoundaryValueDiffEqShooting = "1"
DiffEqBase = "6.167"
DiffEqDevTools = "2.48"
FastClosures = "0.3.2"
ForwardDiff = "0.10.38, 1"
Hwloc = "3.3"
InteractiveUtils = "<0.0.1, 1"
JET = "0.9.18, 0.11.0"
LinearAlgebra = "1.10"
LinearSolve = "3.12"
NonlinearSolveFirstOrder = "1.3"
ODEInterface = "0.5"
OrdinaryDiffEqLowOrderRK = "1.2"
OrdinaryDiffEqTsit5 = "1.1"
Pkg = "1.10.0"
Random = "1.10"
RecursiveArrayTools = "3.31.2"
ReTestItems = "1.29"
Reexport = "1.2"
SciMLBase = "2.120.0"
Sparspak = "0.3.11"
StaticArrays = "1.9.8"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
NonlinearSolveFirstOrder = "5959db7a-ea39-4486-b5fe-2dd0bf03d60d"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Sparspak = "e56a9233-b9d6-4f03-8d0f-1825330902ac"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "DiffEqDevTools", "Hwloc", "InteractiveUtils", "JET", "LinearSolve", "NonlinearSolveFirstOrder", "ODEInterface", "OrdinaryDiffEqLowOrderRK", "OrdinaryDiffEqTsit5", "Pkg", "Random", "ReTestItems", "RecursiveArrayTools", "Sparspak", "StaticArrays", "Test"]
